import { Chess, type Square } from 'chess.js';
import { SYSTEM_DETAILS_MAP, getSystemAnalysis, lostSystemObjective, systemInterference } from './systemObjectives';
import { identifySystem, planSystem, systemGoalScore, type SystemPlan, type SystemAnalyzer, type SystemEngineResult } from './systemsCoordinator';
import { proposeSaferSystem, type SystemProposal } from './rodentAdvisor';
import { canTransitionSystem } from './systemPreferences';
import { cloneChessWithHistory } from '../utils/chessClone';

export type AssistantStatus = 'inactive' | 'calculating' | 'checked' | 'limited' | 'warning' | 'error';
export interface AssistantEvidence { id: string; name: string; status: AssistantStatus; detail: string; evidence: string[] }
export interface SystemThreat {
  fen: string;
  rivalFen: string;
  afterFen: string;
  uci: string;
  san: string;
  reason: string;
  damage: number;
  scoreCp: number;
  verified: boolean;
  afterMain?: string;
  recovery: SystemPlan | null;
  line: string[];
}
export interface SystemsSnapshot {
  fen: string; gameId: string; systemId: string; systemName: string;
  provisional: boolean; loading: boolean; error?: string;
  phase: 'opening' | 'continuation'; transitionLimit: number;
  currentPlan: SystemPlan | null; alternative: SystemPlan | null;
  threat: SystemThreat | null; proposal: SystemProposal | null;
  actualReply?: { san: string; predicted: boolean; detail: string };
  helpers: AssistantEvidence[];
  searches: number; elapsedMs: number; finishedAt?: number;
}
const HELPER_NAMES = [
  ['objectives', 'Objetivos del sistema'], ['rival', 'Respuestas rivales'],
  ['recovery', 'Continuidad y recuperación'], ['safety', 'Seguridad táctica'],
  ['alternatives', 'Alternativas y transiciones'], ['coordination', 'Coordinación'],
] as const;

export function emptySystemsSnapshot(board: Chess, color: 'w' | 'b', selected: string, gameId: string, limit: number, enabled = true): SystemsSnapshot {
  const identified = identifySystem(board, color, selected);
  return { fen: board.fen(), gameId, systemId: identified.id, systemName: identified.name,
    provisional: identified.provisional, loading: enabled, phase: canTransitionSystem(board.fen(), limit) ? 'opening' : 'continuation',
    transitionLimit: limit, currentPlan: null, alternative: null, threat: null, proposal: null,
    searches: 0, elapsedMs: 0,
    helpers: HELPER_NAMES.map(([id, name]) => ({ id, name, status: enabled ? 'calculating' : 'inactive',
      detail: enabled ? 'Esperando el análisis de esta posición.' : 'Se activa al iniciar una partida en modo Sistemas.', evidence: [] })) };
}
function play(board: Chess, uci: string) {
  try { return board.move({ from: uci.slice(0, 2), to: uci.slice(2, 4), promotion: uci[4] }); }
  catch { return null; }
}
function ownScore(result: SystemEngineResult, turn: string, color: string) {
  const score = result.mate !== undefined ? (result.mate > 0 ? 100000 : -100000) : result.scoreCp;
  return turn === color ? score : -score;
}

// Evidence is generated by the actual pipeline; a loaded module is not a completed check.
export async function runSystemAssistants(board: Chess, color: 'w' | 'b', selected: string, mainMove: string | undefined,
  analyzeEngine: SystemAnalyzer, options: {
    gameId?: string; transitionLimit?: number; cancelled?: () => boolean;
    previous?: SystemsSnapshot | null; onProgress?: (value: SystemsSnapshot) => void;
    budgetMs?: number; maxSearches?: number; rivalAnalyzer?: SystemAnalyzer; rivalEngineName?: string;
  } = {}): Promise<SystemsSnapshot | null> {
  const cancelled = options.cancelled || (() => false);
  const started = Date.now();
  const snapshot = emptySystemsSnapshot(board, color, selected, options.gameId || '', options.transitionLimit || 7);
  const cache = new Map<string, Promise<SystemEngineResult | null>>();
  let fallbackSeen = false;
  let truncated = false;
  const analyze: SystemAnalyzer = fen => {
    if (cancelled()) return Promise.resolve(null);
    const cached = cache.get(fen);
    if (cached) return cached;
    if (cache.size >= (options.maxSearches ?? 42) || Date.now() - started >= (options.budgetMs ?? 10000)) {
      truncated = true; return Promise.resolve(null);
    }
    const task = analyzeEngine(fen).then(result => { if (result?.source === 'fallback') fallbackSeen = true; return result; });
    cache.set(fen, task); return task;
  };
  const update = (id: string, status: AssistantStatus, detail: string, evidence: string[] = []) => {
    snapshot.helpers = snapshot.helpers.map(helper => helper.id === id ? { ...helper, status, detail, evidence } : helper);
    snapshot.searches = cache.size; snapshot.elapsedMs = Date.now() - started;
    if (!cancelled()) options.onProgress?.({ ...snapshot });
  };
  const copy = cloneChessWithHistory(board);
  const details = SYSTEM_DETAILS_MAP[snapshot.systemId];
  if (!details || details.color !== color) return null;
  const goals = getSystemAnalysis(copy, snapshot.systemId);
  update('objectives', 'checked', `${snapshot.systemName}: estructura, desarrollo y seguridad; no exige un orden único.`,
    goals.milestones.map(goal => `${goal.title}: ${goal.status === 'completed' ? 'alcanzado' : goal.status === 'in_progress' ? 'en desarrollo' : 'pendiente'}`));
  update('coordination', 'checked', 'Sistema y color compartidos; las propuestas no cambian el sistema sin aceptación.',
    [`Bando: ${color === 'w' ? 'blancas' : 'negras'}`, `Posición: ${snapshot.fen}`, `Partida: ${snapshot.gameId}`]);
  if (copy.isGameOver()) {
    for (const id of ['rival', 'recovery', 'safety', 'alternatives']) update(id, 'checked', 'Partida finalizada. Sin continuaciones legales.');
    snapshot.loading = false; snapshot.finishedAt = Date.now(); return snapshot;
  }
  try {
    const ownTurn = copy.turn() === color;
    if (ownTurn) {
      snapshot.currentPlan = await planSystem(copy, snapshot.systemId, analyze, { preferredMove: mainMove, cancelled });
      if (cancelled()) return null;
      const main = mainMove && copy.moves({ verbose: true }).find(m => m.from + m.to + (m.promotion || '') === mainMove);
      if (main && snapshot.currentPlan?.source === 'wasm') {
        snapshot.alternative = await planSystem(copy, snapshot.systemId, analyze, { alternativeTo: mainMove, strictAlternative: true, cancelled });
        if (snapshot.alternative?.move === mainMove) snapshot.alternative = null;
      }
      const disputedMain = Boolean(main && snapshot.currentPlan?.source === 'wasm' && snapshot.currentPlan.move !== mainMove);
      update('safety', snapshot.currentPlan?.source === 'wasm' ? disputedMain ? 'warning' : 'checked' : 'limited',
        disputedMain ? `La jugada de Garbo no supera el filtro de seguridad de Rodent en esta búsqueda; continuación comprobada: ${snapshot.currentPlan!.san}.`
          : snapshot.currentPlan?.source === 'wasm' ? 'Continuaciones comparadas con respuesta rival por Rodent real.' : 'Sin verificación táctica completa del motor real; no se publica una alternativa.',
        snapshot.currentPlan ? [`Evaluación propia: ${(snapshot.currentPlan.scoreCp / 100).toFixed(2)}`, `Profundidad raíz: ${snapshot.currentPlan.depth}`, snapshot.currentPlan.reason] : []);
      const previous = options.previous;
      const last = copy.history({ verbose: true }).at(-1);
      if (previous?.gameId === snapshot.gameId && previous.systemId === snapshot.systemId && previous.threat &&
        last?.color !== color && last?.before === previous.threat.rivalFen) {
        const predicted = last.from + last.to + (last.promotion || '') === previous.threat.uci;
        snapshot.actualReply = { san: last.san, predicted, detail: predicted
          ? 'El rival jugó la interferencia prevista. El plan se ha recalculado desde la posición real.'
          : 'El rival eligió otra respuesta. Se recalculó su efecto; no se supone que sea mejor solo por ser distinta.' };
      }
    }
    const rivalBoard = cloneChessWithHistory(copy);
    const mainPlayed = ownTurn && mainMove ? play(rivalBoard, mainMove) : null;
    if (!ownTurn || mainPlayed) {
      if (!rivalBoard.isGameOver()) {
        const rivalRoot = await (options.rivalAnalyzer || analyze)(rivalBoard.fen());
        if (cancelled()) return null;
        const move = rivalBoard.moves({ verbose: true }).find(item => item.from + item.to + (item.promotion || '') === rivalRoot?.uci);
        let critical: { move: typeof move & {}; position: Chess; result: SystemEngineResult; reason: string; damage: number } | null = null;
        if (move && rivalRoot?.source === 'wasm') {
          const position = cloneChessWithHistory(rivalBoard); position.move(move);
          const response = position.isGameOver()
            ? { uci: '', scoreCp: position.isCheckmate() ? -100000 : 0, depth: 0, source: 'wasm' as const }
            : await analyze(position.fen());
          const result = response?.source === 'wasm' ? response : { ...rivalRoot, uci: '', scoreCp: ownScore(rivalRoot, rivalBoard.turn(), color), mate: undefined };
          critical = { move, position, result, damage: 0,
            reason: `mejor continuación encontrada por ${options.rivalEngineName || 'Rodent'}, sin restringirla al sistema elegido.` };
        }

        if (critical) {
          const recovery = critical.position.isGameOver() ? null : await planSystem(critical.position, snapshot.systemId, analyze, { cancelled });
          if (cancelled()) return null;
          const line = [...(mainPlayed ? [mainPlayed.san] : []), critical.move.san];
          if (recovery?.source === 'wasm') {
            const follow = cloneChessWithHistory(critical.position);
            if (play(follow, recovery.move)) {
              line.push(recovery.san);
              const counter = follow.isGameOver() ? null : await analyze(follow.fen());
              if (counter?.source === 'wasm') { const counterMove = play(follow, counter.uci); if (counterMove) line.push(counterMove.san); }
            }
          }
          snapshot.threat = { fen: snapshot.fen, rivalFen: rivalBoard.fen(), afterFen: critical.position.fen(),
            uci: critical.move.from + critical.move.to + (critical.move.promotion || ''), san: critical.move.san,
            reason: critical.reason!, damage: critical.damage, scoreCp: ownScore(critical.result, critical.position.turn(), color),
            verified: true, afterMain: mainPlayed?.san, recovery, line };
          update('rival', 'checked', 'Mejor continuación rival encontrada, independiente del sistema.',
            [`Motor rival: ${options.rivalEngineName || 'Rodent'} · Profundidad: ${rivalRoot?.depth || 0}`,
              `${mainPlayed ? `Tras ${mainPlayed.san}, ` : ''}${critical.move.san}: ${critical.reason}`, `Evaluación propia tras la respuesta: ${(critical.result.scoreCp / 100).toFixed(2)}`]);
          update('recovery', recovery?.source === 'wasm' ? recovery.changeNeeded ? 'warning' : 'checked' : 'limited',
            recovery?.source === 'wasm' ? recovery.changeNeeded
              ? `Respuesta defensiva: ${recovery.san}; no se comprobó una recuperación segura del esquema.`
              : `Plan previsto: ${recovery.san}. Se recalcula si el rival lo provoca.` : 'No se comprobó una recuperación suficiente en esta búsqueda.',
            [`Línea posible, no forzada: ${line.join(' → ')}`, ...(snapshot.actualReply ? [snapshot.actualReply.detail] : []), ...(recovery ? [recovery.reason] : [])]);
        } else {
          update('rival', 'limited', 'No se pudo completar la búsqueda real de la mejor respuesta rival; no se inventa una jugada.');
          update('recovery', snapshot.currentPlan?.source === 'wasm' ? 'checked' : 'limited',
            snapshot.currentPlan?.reason || 'Sin plan propio comprobado para esta posición.', snapshot.actualReply ? [snapshot.actualReply.detail] : []);
        }
      } else {
        update('rival', 'checked', 'La continuación termina la partida; no existe una respuesta rival.');
        update('recovery', 'checked', 'No requiere recuperación.');
      }
    } else {
      update('rival', 'limited', 'Sin jugada de Garbo comprobada: no se inventa una respuesta futura.');
      update('recovery', 'limited', 'Esperando una continuación propia comprobada.');
    }
    if (!ownTurn) update('safety', fallbackSeen || truncated ? 'limited' : 'checked', 'Se examinan respuestas rivales; no se recomienda mover por el usuario en turno contrario.');
    if (ownTurn && snapshot.phase === 'opening' && snapshot.currentPlan?.changeNeeded && snapshot.currentPlan.source === 'wasm') {
      snapshot.proposal = await proposeSaferSystem(copy, snapshot.currentPlan, analyze, cancelled);
      if (snapshot.proposal) snapshot.proposal.sourceSystem = selected;
    }
    if (snapshot.alternative?.source !== 'wasm') snapshot.alternative = null;
    update('alternatives', snapshot.proposal ? 'warning' : fallbackSeen || truncated || (ownTurn && snapshot.currentPlan?.source !== 'wasm') ? 'limited' : 'checked',
      snapshot.proposal ? `Transición comprobada a ${snapshot.proposal.name}; pendiente de aceptación manual.`
        : snapshot.alternative ? `Alternativa propia distinta: ${snapshot.alternative.san}.`
        : 'Sin alternativa distinta y suficientemente segura; Rodent no publica una jugada propia.',
      [snapshot.phase === 'opening' ? `Cambios permitidos hasta la jugada ${snapshot.transitionLimit}, si son viables.` : 'Ventana de cambios cerrada; se trabaja sobre el sistema activo.',
        ...(snapshot.alternative ? [snapshot.alternative.reason] : []), ...(snapshot.proposal ? [snapshot.proposal.reason] : [])]);
    if (truncated) update('coordination', 'limited', 'Presupuesto de búsqueda agotado. Se conservan únicamente resultados ya comprobados.', [`${cache.size} posiciones consultadas`, 'No se certifica que se hayan examinado todas las continuaciones.']);
    snapshot.loading = false; snapshot.searches = cache.size; snapshot.elapsedMs = Date.now() - started; snapshot.finishedAt = Date.now();
    return cancelled() ? null : snapshot;
  } catch (error) {
    if (cancelled()) return null;
    snapshot.loading = false; snapshot.error = error instanceof Error ? error.message : 'Error de análisis';
    for (const helper of snapshot.helpers.filter(h => h.status === 'calculating')) update(helper.id, 'error', 'El cálculo no se completó; no se presenta como verificado.');
    snapshot.finishedAt = Date.now(); return snapshot;
  }
}
